/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lionheartheroes.app;

import lionheartheroes.list.LinkedList;

import static lionheartheroes.utilities.StringUtils.join;
import static lionheartheroes.utilities.StringUtils.split;


import spark.ModelAndView;
import spark.template.handlebars.HandlebarsTemplateEngine;

import java.util.HashMap;
import java.util.Map;

import static spark.Spark.*;

public class App {
    public static void main(String[] args) {
        staticFileLocation("/public");

        get("/", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            return new ModelAndView(new HashMap(), "herohub.hbs");
        }, new HandlebarsTemplateEngine());

        get("/squadhub", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            return new ModelAndView(new HashMap(), "squadhub.hbs");
        }, new HandlebarsTemplateEngine());

        get("/heroForm", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            return new ModelAndView(new HashMap(), "heroForm.hbs");
        }, new HandlebarsTemplateEngine());

        get("/squadForm", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            return new ModelAndView(new HashMap(), "squadForm.hbs");
        }, new HandlebarsTemplateEngine());

        post("/squadhub", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            String SquadName = request.queryParams("SquadName");
            String Mission_Control = request.queryParams("Mission_Control");
            int Squad_Size = Integer.parseInt(request.queryParams("Squad_Size"));
            SquadHeroes newTeamSquad = new SquadHeroes(SquadName, Mission_Control, Squad_Size);
            response.redirect("squadhub.hbs");
            return null;
        }, new HandlebarsTemplateEngine());

        post("/", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            String HeroName = request.queryParams("HeroName");
            String Special_Power = request.queryParams("Special_Power");
            String flaw = request.queryParams("flaw");
            int Age = Integer.parseInt(request.queryParams("Age"));
            MyHero newHero = new MyHero(HeroName, Special_Power, flaw, Age);
            response.redirect("herohub.hbs");
            return null;
        }, new HandlebarsTemplateEngine());
    }
}
