/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lionheartheroes.app;

import lionheartheroes.list.LinkedList;

import static lionheartheroes.utilities.StringUtils.join;
import static lionheartheroes.utilities.StringUtils.split;
import static lionheartheroes.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
